# define the parameters that will be used to decide which jobs to be generated and run the dynamic configuration
parameters:
  always-continue:
    type: boolean
    default: false
  build-code:
    type: boolean
    default: false
  build-docs:
    type: boolean
    default: false
