# this is the main setup file for dynamic configuration
version: 2.1
parameters:
  run-trigger-api:
    type: boolean
    default: false
jobs:
  trigger-api:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --no-cache curl
      # best practice using Personal API tokens for business use case:
      # https://circleci.com/docs/guides/integration/github-integration/#controlling-access-via-a-machine-user
      # can't use PROJECT_TOKEN api token to trigger pipeline only needed personal access api token
      # https://circleci.com/docs/guides/toolkit/managing-api-tokens/
      # https://circleci.com/docs/guides/toolkit/api-developers-guide/#example-end-to-end-api-request

      # https://circleci.com/docs/guides/orchestrate/triggers-overview/#run-a-pipeline-using-the-api - trigger pipeline guide
      # https://circleci.com/blog/triggering-pipelines-from-pipelines/
      - run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_API_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/arsalanshaikh13/Parallax-Provider-Tutorial/actions/workflows
# the setup workflow that runs first on everypipeline
workflows:
  trigger-api-setup:
    when: << pipeline.parameters.run-trigger-api>>
    jobs:
      - trigger-api
