# this is the main setup file for dynamic configuration
version: 2.1

#this is the required directive to enable dynamic configuration
setup: true

# Use the path-filtering orb to check for changed files
orbs:
  path-filtering: circleci/path-filtering@2.0.2

# the setup workflow that runs first on everypipeline
workflows:
  path-filtering-setup:
    jobs:
      - path-filtering/filter:
          # Use this pipeline variable to compare against the previous commit
          # on the current branch that triggered the pipeline

          base-revision: alpine-branch
          # this is the path to the second configuration file to run
          config-path: .circleci/config_api.yml
          # Define the mapping of regex patterns to pipeline parameters
          mapping:
            # Trigger the build_and_release workflow for this file extenisons
            # this regex will match any .js, .json, .yml, or .rc
            .*\.yml run-trigger-api true
          # by default path-filter always works for branches so no need for mentioning filter branch
          # filters is only required for tag push
